project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "slides/*.qmd"

website:
  title: "FRA2261-A-H26 - Dramaturgie d'Ancien RÃ©gime"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
      - href: corneille.qmd
      - href: moliere.qmd
      - href: poetique.qmd
      - href: bibliographie.qmd
      #- href: racine.qmd
      #- href: bernard.qmd
      #- href: villedieu.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

lang: fr-FR

bibliography: bibliographie.bib
csl: apa.csl



