project:
  type: book
  output-dir: _site
  render:
    - index.qmd
    - intro.qmd
    - corneille.qmd

website:
  title: "FRA2261-A-H26 - Dramaturgie d'Ancien RÃ©gime"
#  navbar:
 #   left:
  #    - href: index.qmd
   #     text: Home
    #  - href: intro.qmd
  #    - href: corneille.qmd
   #   - href: moliere.qmd
   #   - href: racine.qmd
   #   - href: bernard.qmd
   #   - href: villedieu.qmd
   #   - href: bibliographie.qmd
   chapters:
    - index.qmd
    - intro.qmd
    - corneille.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

lang: fr-FR



